spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8087/
            predicates:
              - Path=/customers/**
          - id: r2
            uri: http://localhost:8088/
            predicates:
              - Path=/accounts/**

server:
  port: 8888

